"""
PROV-02 — Pre-Boot Server Scaffolding.

Creates the server environment BEFORE the first JVM launch:
  - eula.txt (pre-accepted)
  - server.properties with the assigned port
  - Essential directories: mods/, plugins/, world/, logs/

This eliminates the "EULA Crash" cycle and ensures the server starts
cleanly on the very first boot.
"""

import logging
import os

logger = logging.getLogger(__name__)

# Directories to create inside every new server
_SCAFFOLD_DIRS = ("mods", "plugins", "world", "logs")


def pre_boot_scaffold(server_dir: str, port: int = 25565, eula_accepted: bool = True):
    """Prepare a server directory for a clean first boot.

    Generates eula.txt, a minimal server.properties, and standard
    subdirectories. Safe to call multiple times — existing files are
    never overwritten (port is patched in-place if server.properties
    already exists).

    Args:
        server_dir:     Absolute path to the server root.
        port:           The server-port value to inject.
        eula_accepted:  Whether the user has accepted the Mojang EULA.
    """
    if not os.path.isdir(server_dir):
        logger.warning("Scaffolder: directory does not exist: %s", server_dir)
        return

    _generate_eula(server_dir, eula_accepted)
    _generate_properties(server_dir, port)
    _create_directories(server_dir)

    logger.info("Scaffolding complete for %s", server_dir)


def _generate_eula(server_dir: str, accepted: bool):
    """Write eula.txt if it does not exist yet."""
    eula_path = os.path.join(server_dir, "eula.txt")
    if os.path.exists(eula_path):
        return

    eula_value = "true" if accepted else "false"
    with open(eula_path, "w", encoding="utf-8") as f:
        f.write(
            "#By changing the setting below to TRUE you are indicating "
            "your agreement to our EULA (https://aka.ms/MinecraftEULA).\n"
            "#Pre-generated by ZeroBlockBridge Scaffolder\n"
            f"eula={eula_value}\n"
        )
    logger.info("Generated eula.txt (accepted=%s) in %s", accepted, server_dir)


def _generate_properties(server_dir: str, port: int):
    """Write or patch server.properties with the assigned port."""
    props_path = os.path.join(server_dir, "server.properties")

    if not os.path.exists(props_path):
        # Fresh file with safe defaults
        with open(props_path, "w", encoding="utf-8") as f:
            f.write(
                "#Minecraft server properties\n"
                "#Pre-generated by ZeroBlockBridge Scaffolder\n"
                f"server-port={port}\n"
                "motd=A ZeroBlockBridge Server\n"
                "enable-query=false\n"
                "enable-rcon=false\n"
            )
        logger.info("Generated server.properties (port=%d) in %s", port, server_dir)
        return

    # File exists — patch server-port in place
    try:
        with open(props_path, "r", encoding="utf-8") as f:
            lines = f.readlines()

        port_found = False
        for i, line in enumerate(lines):
            if line.startswith("server-port="):
                lines[i] = f"server-port={port}\n"
                port_found = True
                break

        if not port_found:
            lines.append(f"server-port={port}\n")

        with open(props_path, "w", encoding="utf-8") as f:
            f.writelines(lines)
        logger.info("Patched server-port=%d in existing server.properties", port)
    except Exception as e:
        logger.error("Failed to patch server.properties: %s", e)


def _create_directories(server_dir: str):
    """Ensure the standard server subdirectories exist."""
    for folder in _SCAFFOLD_DIRS:
        os.makedirs(os.path.join(server_dir, folder), exist_ok=True)
