"""
PROV-02 — Pre-Boot Server Scaffolding.

Creates the server environment BEFORE the first JVM launch:
  - eula.txt (pre-accepted)
  - server.properties with the assigned port
  - Essential directories: mods/, plugins/, world/, logs/

This eliminates the "EULA Crash" cycle and ensures the server starts
cleanly on the very first boot.
"""

import logging
import os

logger = logging.getLogger(__name__)

# Directories to create inside every new server
_SCAFFOLD_DIRS = ("mods", "plugins", "world", "logs")


def pre_boot_scaffold(server_dir: str, port: int = 25565, eula_accepted: bool = True, config: dict = None):
    """Prepare a server directory for a clean first boot.

    Generates eula.txt, a minimal server.properties, and standard
    subdirectories. Safe to call multiple times — existing files are
    never overwritten (port is patched in-place if server.properties
    already exists).

    Args:
        server_dir:     Absolute path to the server root.
        port:           The server-port value to inject (1-65535).
        eula_accepted:  Whether the user has accepted the Mojang EULA.
        config:         Optional dict containing advanced properties.

    Raises:
        ValueError: If port is outside valid range.
    """
    if not (1 <= port <= 65535):
        raise ValueError(f"Invalid port: {port}. Must be between 1 and 65535.")
    if not os.path.isdir(server_dir):
        logger.warning("Scaffolder: directory does not exist: %s", server_dir)
        return

    _generate_eula(server_dir, eula_accepted)
    _generate_properties(server_dir, port, config)
    _create_directories(server_dir)

    logger.info("Scaffolding complete for %s", server_dir)


def _generate_eula(server_dir: str, accepted: bool):
    """Write eula.txt if it does not exist yet."""
    eula_path = os.path.join(server_dir, "eula.txt")
    if os.path.exists(eula_path):
        return

    eula_value = "true" if accepted else "false"
    with open(eula_path, "w", encoding="utf-8") as f:
        f.write(
            "#By changing the setting below to TRUE you are indicating "
            "your agreement to our EULA (https://aka.ms/MinecraftEULA).\n"
            "#Pre-generated by ZeroBlockBridge Scaffolder\n"
            f"eula={eula_value}\n"
        )
    logger.info("Generated eula.txt (accepted=%s) in %s", accepted, server_dir)


# Maps config dict key -> (server.properties key, value transform)
_CONFIG_PROPERTY_MAP = {
    "game_mode": ("gamemode", str),
    "difficulty": ("difficulty", str),
    "hardcore": ("hardcore", lambda v: "true" if v else "false"),
    "whitelist": ("white-list", lambda v: "true" if v else "false"),
    "enforce_whitelist": ("enforce-whitelist", lambda v: "true" if v else "false"),
    "pvp": ("pvp", lambda v: "true" if v else "false"),
    "online_mode": ("online-mode", lambda v: "true" if v else "false"),
    "max_players": ("max-players", str),
    "spawn_protection": ("spawn-protection", str),
    "enable_command_block": ("enable-command-block", lambda v: "true" if v else "false"),
    "allow_flight": ("allow-flight", lambda v: "true" if v else "false"),
    "enforce_secure_profile": ("enforce-secure-profile", lambda v: "true" if v else "false"),
    "view_distance": ("view-distance", str),
    "simulation_distance": ("simulation-distance", str),
}


def _generate_properties(server_dir: str, port: int, config: dict = None):
    """Write or patch server.properties with the assigned port and config."""
    props_path = os.path.join(server_dir, "server.properties")

    props_to_write = {
        "server-port": str(port),
        "motd": "A ZeroBlockBridge Server",
        "enable-query": "false",
        "enable-rcon": "false"
    }

    if config:
        if config.get("seed"):
            props_to_write["level-seed"] = str(config["seed"])
        for config_key, (props_key, transform) in _CONFIG_PROPERTY_MAP.items():
            if config_key in config:
                props_to_write[props_key] = transform(config[config_key])

    if not os.path.exists(props_path):
        os.makedirs(os.path.dirname(props_path), exist_ok=True)
        with open(props_path, "w", encoding="utf-8") as f:
            f.write("#Minecraft server properties\n")
            f.write("#Pre-generated by ZeroBlockBridge Scaffolder\n")
            for k, v in props_to_write.items():
                f.write(f"{k}={v}\n")
        logger.info("Generated server.properties (port=%d) in %s", port, server_dir)
        return

    try:
        with open(props_path, "r", encoding="utf-8") as f:
            lines = f.readlines()

        existing_keys = set()
        for i, line in enumerate(lines):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            key = stripped.split("=")[0]
            existing_keys.add(key)
            if key == "server-port":
                lines[i] = f"{key}={props_to_write[key]}\n"
                del props_to_write[key]
            elif key in props_to_write:
                del props_to_write[key]

        for k, v in props_to_write.items():
            lines.append(f"{k}={v}\n")

        with open(props_path, "w", encoding="utf-8") as f:
            f.writelines(lines)
        logger.info("Patched properties in existing server.properties")
    except Exception as e:
        logger.error("Failed to patch server.properties: %s", e)


def _create_directories(server_dir: str):
    """Ensure the standard server subdirectories exist."""
    for folder in _SCAFFOLD_DIRS:
        os.makedirs(os.path.join(server_dir, folder), exist_ok=True)
