from typing import Protocol, Any, Optional

class EventEmitterProtocol(Protocol):
    def emit(self, event_type: Any, data: Any = None) -> None: ...
    def subscribe(self, event_type: Any, callback: Any) -> None: ...
    def unsubscribe(self, event_type: Any, callback: Any) -> None: ...

class ServerRunnerProtocol(Protocol):
    @property
    def running(self) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def send_command(self, command: str) -> None: ...

class BackupServiceProtocol(Protocol):
    def create_backup(self, retention_count: Optional[int] = None) -> tuple[Optional[Any], Optional[str]]: ...

class ServerOrchestratorProtocol(Protocol):
    def start_server(self) -> bool: ...
    def stop_server(self) -> None: ...
    def is_running(self) -> bool: ...
    def send_command(self, cmd: str) -> None: ...

class BackupOrchestratorProtocol(Protocol):
    def _check_auto_backup(self) -> None: ...
    def _run_auto_backup(self) -> None: ...

class TunnelOrchestratorProtocol(Protocol):
    def start_tunnel(self) -> None: ...
    def stop_tunnel(self) -> None: ...
    def reset_tunnel(self, mode: str) -> None: ...
    def get_tunnel_ip(self) -> Optional[str]: ...
    def create_tunnel_for_server(self, server_name: str) -> None: ...

class SchedulerOrchestratorProtocol(Protocol):
    def _start_tick_loop(self) -> None: ...
